name: CI Examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  examples-building-and-testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Continue other jobs if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        folder:
          - examples/database/src
          - examples/etag/src
          - examples/hexagonal/src
          - examples/io_uring_demo/src
          - examples/simple/src
          - examples/simple2/src
          - examples/sse/src
    steps:
      - uses: actions/checkout@v4
      - name: Set up V
        uses: vlang/setup-v@v1.4
      - name: Remove Vlang folder to avoid conflicts
        run: rm -rf -v ./vlang || true
      - name: Install dependencies
        shell: bash
        run: |
          set -e
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y libsqlite3-dev liburing-dev linux-libc-dev
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew update
            brew install sqlite3
          fi
      - name: Build ${{ matrix.folder }}
        shell: bash
        run: |
          set -e
          v "${{ matrix.folder }}"
      - name: Test ${{ matrix.folder }}
        shell: bash
        run: |
          set -e
          v test "${{ matrix.folder }}"
